"""Rename Names to name_of_the_staff in faculty _information

Revision ID: 1eaa5e36a73f
Revises: 45349613ddc5
Create Date: 2024-01-19 09:24:39.000453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1eaa5e36a73f'
down_revision = '45349613ddc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Faculty_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pan_no', sa.String(length=255), nullable=True),
    sa.Column('name_of_the_staff', sa.String(length=255), nullable=True),
    sa.Column('bank_account', sa.Integer(), nullable=True),
    sa.Column('ifsc_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Faculty_information', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Faculty_information_pan_no'), ['pan_no'], unique=False)

    op.create_table('Subject_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=255), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Examination_bills',
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('pan_no', sa.String(length=255), nullable=True),
    sa.Column('name_of_the_staff', sa.String(length=255), nullable=True),
    sa.Column('bank_account_no', sa.Integer(), nullable=True),
    sa.Column('ifsc_code', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.String(length=255), nullable=True),
    sa.Column('no_of_scripts', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pan_no'], ['Faculty_information.pan_no'], ),
    sa.PrimaryKeyConstraint('examination_id')
    )
    op.drop_table('examination_bills')
    op.drop_table('subject_information')
    with op.batch_alter_table('faculty_information', schema=None) as batch_op:
        batch_op.drop_index('ix_Faculty_information_pan_no')

    op.drop_table('faculty_information')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_information',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pan_no', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Names', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bank_account', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('faculty_information', schema=None) as batch_op:
        batch_op.create_index('ix_Faculty_information_pan_no', ['pan_no'], unique=False)

    op.create_table('subject_information',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('subject_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('subject_name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('examination_bills',
    sa.Column('examination_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pan_no', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name_of_the_staff', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bank_account_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('transaction_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('no_of_scripts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('grand_total', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['pan_no'], ['faculty_information.pan_no'], name='examination_bills_ibfk_1'),
    sa.PrimaryKeyConstraint('examination_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Examination_bills')
    op.drop_table('Subject_information')
    with op.batch_alter_table('Faculty_information', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Faculty_information_pan_no'))

    op.drop_table('Faculty_information')
    # ### end Alembic commands ###
